services:
  gate-server:
    build:
      context: .
    container_name: gate-server
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:8010:8000"